spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        - id: onboarding-service
          uri: lb://onboarding-service
          predicates:
            - Path=/api/onboarding/**
          filters:
            - StripPrefix=1
        - id: login-service
          uri: lb://login-service
          predicates:
            - Path=/login/**
          filters:
            - StripPrefix=1
        - id: dashboard-service
          uri: lb://dashboard-service
          predicates:
            - Path=/dashboard/**
          filters:
            - StripPrefix=1
        - id: bills-service
          uri: lb://bills-service
          predicates:
            - Path=/bills/**
          filters:
            - StripPrefix=1

server:
  port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
