spring:
  application:
    name: bills-service
  datasource:
    url: jdbc:mysql://localhost:3306/bills_payment
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: cassillas1nengi
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    preferIpAddress: true

logging:
  level:
    org:
      hibernate:
        SQL: debug
        type: trace
server:
  port: 8200
